### ISSUE TITLE
Override sneak with 'Fly Down' when using hold-to-fly.

### ISSUE THREAD

**Issue by corviale** [DaFlight/DaFlightLiteloader#13]
When FlyDown is set to the same key as sneak, FlyDown does not behave properly when using fly mode in hold-key mode. (It does not move the player downward until the FlyDown key is held for about one second; Downward movement is jagged/inconsistent.)

**Comment by dags-** [comment]
Can't recreate the issue.
What version of daflight are you using and for what version of minecraft? Are you running with any other mods?

**Comment by corviale** [comment]
Oops, I now see there is another issue listed here about mouse input. I was using a mouse button to toggle fly; Binding it to the keyboard does not produce the issue.
version: 21r2

**Comment by dags-** [comment]
Ahh right thanks, I'll keep this open anyway as something to check when I add mouse button support

**Comment by dags-** [comment]
Closing this on the assumption that the new Mouse binding feature is compatible. Let me know if not
