### ISSUE TITLE
Cannot noclip in gamemode 3 in multiplayer

### ISSUE THREAD

**Issue by kosakriszi** [DaFlight/DaFlightLiteloader#15]
The title pretty much says it all. Ever since the introduction of the noclip feature in singleplayer, I haven't been able to clip through blocks in gamemode 3.

**Comment by dags-** [comment]
Thanks, will fix.

Note to self:
https://gist.github.com/972aad6b69f359af80b8

**Comment by dags-** [comment]
fixed in 2.4r5 - thanks again for bringing this to my attention :]
