### ISSUE TITLE
Option to have 2DaFlight ignore "Jump" and "Sneak" keys

### ISSUE THREAD

**Issue by Barhandar** [DaFlight/DaFlightLiteloader#7]
Modded Minecraft requires one to hold "Sneak" to place blocks without interacting quite a bit of time.
It's hard to do accurately while moving down, so I would rather have an option to not move down while sneaking, even if that means sneaking will pin me in midair.

My ascent and descent hotkeys are separate from jumping and sneaking. 
P.S. Note that it's currently possible to hold steady by holding both "Jump" and "Sneak", but it's clunky, not always possible, and results in position shifting most of the time due to imperfect timing.)

**Comment by Barhandar** [comment]
"Mostly" is insufficient. Jerking on pressing "Jump" or "Sneak" is worse than moving, because it can't be reliably counteracted.

**Comment by dags-** [comment]
Right, well I'm sorry that this is insufficient for you.
